[[sec_5]]
== Geo Features -- Natural Features

The use of Global Navigation Satellite Systems (GNSS) as an integral
component of ECDIS has raised questions as to the level of topographic
detail that is required in ENCs to enable safe navigation using ECDIS.
When determining the topographic information necessary for inclusion
in ENC, all operational conditions of vessels must be taken into consideration,
including the potential for corruption or failure of a vessel's GNSS
reception. Such a failure would require the Mariner to navigate by
fixing their position using traditional methods, necessitating a sufficient
level of depiction of topographic detail in the ENC to facilitate
navigation using these methods, appropriate to the Navigational Purpose
of the ENC.

In addition, Mariners will continue to use visual or radar fixing
as an independent method of confirming the position of their vessel
as shown on the ECDIS, in order to gain a greater level of confidence
in terms of their navigation.

Encoders are advised, therefore, that when determining the level of
depiction of topographic detail required for ENC, this should be done
in accordance with the following principles:

* The types of features charted and the distance inland to which they
are shown will vary with the optimum display scale of the ENC data,
type of terrain, availability of source data and, possibly, adequacy
of regular navigational aids. The significance to the Mariner must
be judged by the requirements of both visual and radar navigation.
* The navigator sees the coast in profile; the cartographer compiles
it in plan and must always be aware that the navigator's interest
in land detail is at its greatest at the coastline and falls off rapidly
inland. On a low-lying coast, even minor clues to position near the
coast, for example sand dunes, hillocks, low bluffs, may be very useful
on most detailed ENC datasets. On steep coasts with deep water close
inshore, sea traffic is likely to be concentrated off projecting points
of land, and the nature of each headland must be made clear, whether
it has vertical cliffs, or a sloping or low profile, for example.
* Off coasts inadequately marked by navigational aids, detailed topography
in the coastal belt will allow the Mariner to clear dangers with the
aid of improvised visual transits of charted topographical features.

No definite standards can be stated but the following principles should
be observed:

* The density of topographic detail shown should be kept to a minimum
consistent with providing navigators with all identifiable features
and with a general picture of the relief as far as the probable skyline.
This practice should enable landmarks to stand out from less important
detail.
* Treatment of detail should vary with distance inland, for example
inconspicuous features such as marshes and minor lakes and streams
should be shown only when within about a mile of the coast.

Additional guidance regarding the level of depiction of topographic
detail in regard to specific features is included in the following
clauses.

[[sec_5.1]]
=== Cliffs (see S-4 -- B-312.3)

A coast backed by rock or earth cliffs gives a good radar return and
is useful for visual identification from a considerable distance off,
where cliffs alternate with low lying coast along the shoreline. Where
cliffs are prominent features they should be encoded on the larger
optimum display scale for the ENC data; as an exception, where cliffs
predominate over extensive stretches of coastline, it may be neither
feasible nor particularly useful to insert a cliff throughout. Cliff
top heights are useful for calculating or estimating distance off,
(for clearing inshore dangers) and should be encoded where possible.

If it is required to encode a non-coastal cliff, it must be done using
the feature *Sloping Ground* (see <<sec_5.14>>) and/or using the feature
*Slope Topline* (see <<sec_5.15>>), with attribute
stem:[bb "category of slope" = 6] (cliff). For example:

*Sloping Ground* may be used at large scale to indicate the horizontal
extent of the cliff.

*Slope Topline* should be used on its own to encode cliffs at small
scale, or in conjunction with *Sloping Ground* to indicate the crest
of the cliff when it is considered useful to know its elevation, and/or
to encode a cliff on land distant from the coastline.

[underline]#Remarks:#

* When the cliff is coincident with the coastline, a *Coastline* feature,
with attribute stem:[bb "category of coastline" = 1] (steep coast)
should be encoded, and there should be no *Sloping Ground* or
*Slope Topline* encoded.

[[sec_5.2]]
=== Cuttings and embankments (see S-4 -- B-363.2 and B-364.1)

If it is required to encode cuttings and embankments, this must be
done in the same way as cliffs; using *Sloping Ground* and/or
*Slope Topline* features (see <<sec_5.14;and!sec_5.15>>), with attribute
stem:[bb "category of slope" = 1] (cutting) or _2_ (embankment).

[underline]#Remarks:#

* Cuttings and embankments should be encoded only when likely to be
visible from seaward.

[[sec_5.3]]
=== Coastline

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *COASTLINE*. The line where shore
and water meet. Shoreline and coastline are generally used synonymously.
(IHO Dictionary -- S-32).
10+| *[underline]#S-101 Geo Feature:#* *Coastline (COALNE)*
10+| *[underline]#Primitives:#* *Curve*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of coastline 2+| (CATCOA) 3+|
1: steep coast +
2: flat coast +
6: glacier, seaward end +
7: mangrove +
8: marshy shore +
10: ice coast | EN | 0,1
3+| colour 2+| (COLOUR) 3+|
1: white +
2: black +
3: red +
4: green +
6: yellow +
7: grey +
8: brown +
11: orange +
13: pink | EN | 0,*

3+| elevation 2+| (ELEVAT) 3+| | RE | 0,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN | 0,1 footnoteblock:[five_three]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| nature of surface 2+| (NATSUR) 3+|
1: mud +
2: clay +
3: silt +
4: sand +
5: stone +
6: gravel +
7: pebbles +
8: cobbles +
9: rock +
11: lava +
14: coral +
17: shells | EN | 0,*
3+| radar conspicuous 2+| (CONRAD) 3+| | BO | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_three]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_three]

3+| pictorial representation 2+| (PICREP) 3+| See <<sec_2.4.12.2>> | TE | 0,1
10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_three]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 1-8, 25, 32-33

[[sec_5.3.1]]
==== Coastline (see S-4 -- B-310 and B-311)

Natural sections of coastlines, lakeshores and riverbanks should be
encoded as *Coastline*, whereas artificial sections of coastlines,
lakeshores, riverbanks, canal banks and basin borders should be encoded
as *Shoreline Construction* (see <<sec_8.6>>). The exception to this
general rule is when a lake, river, canal, or basin is not navigable
at the optimum display scale for the ENC data, in which case the boundary
of the lake, river, canal, or basin must not be encoded as *Coastline*
or *Shoreline Construction* as the boundary of these specific areas
(*Lake*, *River*, *Canal*, *Dock Area*, *Lock Basin*) create the portrayal
of the bank or shoreline.*Coastline* and *Shoreline Construction*
features form the border of the *Land Area* feature (see <<sec_5.4>>).

[[sec_5.3.2]]
==== Natural coastline (see S-4 -- B-312 and B-353.8)

Spatial types associated with coastlines considered to be inadequately
surveyed at the optimum display scale for the ENC data (see S-4 --
B-311) should be encoded using spatial attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate).

If it is required to encode a description of the nature of the coastline,
it must be done using the attributes *category of coastline* and *nature
of surface*. Other surface features may be used to describe the land
region adjacent to the coastline (see <<sec_5.11>>).

A steep coast may give a good radar return and is useful for visual
identification from a considerable distance off, particularly where
cliffs alternate with low lying coast along the shoreline.

[underline]#Remarks:#

* *Coastline* must only exist at the boundary of *Land Area* of type
surface.
* *Coastline* and *Shoreline Construction* of type curve must not
overlap. Similarly, *Coastline* should not share an edge with a *Shoreline
Construction* of type surface (see <<sec_8.6>>) having attribute *water
level effect* undefined or populated with the values _2_ (always dry)
or _1_ (partly submerged at high water), which is covered by *Land
Area*.
* If the seaward edge of an encoded saltpan area is coincident with
the coastline, it should be encoded using *Coastline*, with
stem:[bb "category of coastline" = 2] (flat coast).
* If the seaward edge of a marsh area or glacier is coincident with
the coastline, the coastline should be encoded as *Coastline*, with
attribute stem:[bb "category of coastline" = 8] (marshy shore) or
_9_ (glacier, seaward end). The coastline's spatial type should have
the attribute stem:[bb "quality of horizontal measurement" = 4] (approximate).
If it is required to encode the area behind the coastline, this must
be done using a *Land Region* feature (for marsh -- see <<sec_5.11.1.1>>)
or an *Ice Area* feature (for glacier -- see <<sec_5.13>>).
* If it is required to encode mangroves in the intertidal area, this
should be done using an *Obstruction* feature (see <<sec_13.6>>).
However, on smaller optimum display scale ENC datasets where the mangroves
are required to be encoded to indicate the seaward edge of a mangrove
area only as the "apparent" coastline, this must be done using *Coastline*
with stem:[bb "category of coastline" = 7] (mangrove). The coastline's
spatial type should have the attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate).
* Where the source indicates the top of a cliff is coincident with
the coastline at the optimum display scale of the ENC data, a *Coastline*
feature, with stem:[bb "category of coastline" = 1] (steep coast)
should be encoded. In such cases, there should be no *Slope Topline*
or *Sloping Ground* features encoded, in order to avoid clutter. If
it is required to indicate that such a section of the coastline provides
a good radar return, it must be done using attribute *radar conspicuous*
on the *Coastline* feature. If it is required to encode a section
of the coastline that is visually conspicuous, it must be done using
attribute *visual prominence* on the *Coastline* feature.
* If the source indicates that the top of a coastal cliff is offset
inshore from the coastline at the optimum display scale of the ENC
data, a *Slope Topline* feature (see <<sec_5.15>>) and/or a *Sloping
Ground* feature (see <<sec_5.14>>) may be encoded. In such cases,
the *Coastline* feature should not have a value populated for
*category of coastline*. If it is required to indicate that such a
section of the coastline provides a good radar return, it must be
done using attribute *radar conspicuous* on the *Slope Topline* and/or
*Sloping Ground* feature. If it is required to encode a section of
the coastline that is visually conspicuous, it must be done using
attribute *visual prominence* on the *Slope Topline* and/or
*Sloping Ground* feature.

[underline]#Distinction:# Shoreline Construction; Slope Topline; Sloping
Ground.

[[sec_5.4]]
=== Land area

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *LAND AREA*. The solid portion of
the Earth's surface, as opposed to sea, water. (IHO Dictionary --
S-32).
10+| *[underline]#S-101 Geo Feature:#* *Land Area (LNDARE)*
10+| *[underline]#Primitives:#* *Point, Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| condition 2+| (CONDTN) 3+|
1: under construction +
3: under reclamation +
5: planned construction | EN | 0,1
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_four]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| reported date 2+| _(SORDAT)_ 3+| See <<sec_2.4.8>> | TD | 0,1
3+| status 2+| (STATUS) 3+|
18: existence doubtful | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_four]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_four]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Component 3+| *Island Aggregation* (see <<sec_25.9>>) 3+| *Island Group* 2+| Association | 0,*
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_four]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# K 10

[[sec_5.4.1]]
==== Land area

Land areas that are never covered by the sea must be encoded using
the feature *Land Area*. *Land Area* features of type surface are
part of the Skin of the Earth.

Rivers, canals, lakes, basins and docks, which are not navigable at
the optimum display scale for the ENC data, must be encoded on top
of *Land Area* features (see <<sec_5.4>>).

[underline]#Remarks:#

* If it is required to describe the natural scenery of the land, it
must be done using the feature *Land Region* (see <<sec_5.11>>).
* *Land Area* is usually of type surface; it may, however, be of type
point (for example islet, rock that does not cover), or of type curve
(for example islet, offshore bar, isthmus).
* *Land Area* of type curve or point must not be encoded on top of
*Land Area* of type surface, unless it is also covered by a *Lake*,
*River*, *Dock Area*, *Lock Basin* or *Canal* feature of type surface.
* The limits of a *Land Area* of type surface must share the geometry
of at least one of the following features:

** *Coastline*, *Shoreline Construction*, *Gate*, *Dam* of type curve;
** *Data Coverage*, *Dolphin*, *Gate*, *Dam*, *River*, *Tunnel*,
*Dry Dock*, *Canal*, *Lake*, *Lock Basin*, *Dock Area*, *Land Area*
of type surface;
** *Causeway*, *Shoreline Construction*, *Wreck*, *Obstruction*,
*Pylon/Bridge Support* of type surface; and having attribute
stem:[bb "water level effect" = 1] (partly submerged at high water),
_2_ (always dry) or _6_ (subject to inundation or flooding).

[[sec_5.4.2]]
==== Rocks which do not cover (islets) (see S-4 -- B-421.1)

A surface feature must be encoded using:

* A *Land Area* feature of type surface (mandatory)
* *Coastline* or *Shoreline Construction* features of type curve (mandatory)
* *Land Elevation* features of type curve and/or point (optional)
A curve feature must be encoded using:

* A *Land Area* feature of type curve (mandatory)
* *Land Elevation* features of type point (optional)
A point feature must be encoded using:

* A *Land Area* feature of type point (mandatory)

* A *Land Elevation* feature of type point (optional)

[underline]#Distinction:# Canal; Coastline; Depth Area; Lake; Land
Region; River; Seabed Area; Shoreline Construction; Vegetation.

[[sec_5.5]]
=== Island group

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *ISLAND GROUP*. A named group of
islands, including archipelagos.
10+| *[underline]#S-101 Geo Feature:#* *Island Group* *_(C_AGGR)_*
10+| *[underline]#Primitives:#* *Surface, None*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 1,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_five]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_five]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_five]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Collection 3+| *Island Aggregation* (see <<sec_25.9>>) 3+| *Land Area*, *Island Group* 2+| Aggregation | 0,1
| The Component 3+| *Island Aggregation* (see <<sec_25.9>>) 3+| *Land Area*, *Island Group* 2+| Association | 0,*
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_five]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:#

[[sec_5.5.1]]
==== Island groups

If it is required to encode the name of a group of islands, it must
be done using the feature *Island Group* of type surface, associated
with all relevant *Land Area* features (see <<sec_5.4>>) included
in the named group of islands using the association *Island Aggregation*
(see <<sec_25.9>>).

[underline]#Remarks:#

* The extent of the surface should cover the extent of all the islands
contained in the named group of islands.
* If it is required to encode the extent of an unnamed group of islands,
this may be done using an *Island Group* feature having no geometry,
associated with all relevant *Land Area* features included in the
group of islands using the association *Island Aggregation*.
* Names of individual islands within an island group must be encoded
using the attribute *feature name* on the relevant *Land Area* feature.

[underline]#Distinction:# Land Area; Land Region.

[[sec_5.6]]
=== Land elevation

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *LAND ELEVATION*. An elevation is
the vertical distance of a point or a level, on, or affixed to, the
surface of the earth, measured from a specified vertical datum.
(Adapted from IHO Dictionary -- S-32).
10+| *[underline]#S-101 Geo Feature:#* *Land Elevation (LNDELV)*
10+| *[underline]#Primitives:#* *Point, Curve*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| elevation 2+| (ELEVAT) 3+| | RE | 1,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_six]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_six]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_six]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_six]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 10-13

[[sec_5.6.1]]
==== Height contours, spot heights (see S-4 -- B-351 and B-352.1-2)

It is assumed that Mariners will understand most methods of representation
of relief with little difficulty. In general, it is assumed that Producing
Authorities will choose the representation of relief most suitable
to the terrain being charted and the navigational requirements. It
is therefore left to national discretion to:

* omit all relief representation, except dykes and sea walls;
* omit all relief representation, except spot heights and cliffs;
* show relief by contours (and spot heights); or
* show relief by form lines (and spot heights).
Spot heights on ENC datasets should be confined to summits of hills,
mountains and cliffs, particularly on datasets from which contours
and form lines have been omitted; navigators will generally assume
that heights selected for ENC are summits.

If it is required to encode a height contour or spot height, it must
be done using the feature *Land Elevation*.*Land Elevation* features
must be covered by a *Land Area* feature of type surface; or a *Wreck*
feature of type surface having attribute
stem:[bb "water level effect" = 1] (partially submerged at high water)
or _2_ (always dry); or fall on a *Land Area* feature of type curve;
or share the geometry of a *Land Area* of type point or a *Wreck*
feature of type point having attribute
stem:[bb "water level effect" = 1] (partially submerged at high water)
or _2_ (always dry). Spatial types associated with approximate contours
or spot heights should be encoded using the attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate).

[underline]#Remarks:#

* Where it would not be worthwhile to contour ENC data of smaller
optimum display scale, form lines (emphasizing a few 'remarkable'
hills) and/or spot heights may be used to emphasize individual features.
* Contours should reflect the nature of the topography; that is, they
should not be rounded or smoothed (by generalisation) when they should
really be angular.
* The contour intervalmust be uniform for any dataset, or series of
datasets of the same or similar optimum display scale, except that
the lowest contour may be a supplementaryone, for example 25 metres
where the basic interval is every 50 metres; or 10 metres where the
basic interval is every 25 metres. Ideally the contour interval should
be chosen so that not more than 10 contours are needed for the full
range of height on a single dataset or particular series of datasets
(for clarity and economy).
* If it is required to encode the elevation of an observation spot,
benchmark or horizontal control station, it must be done using
*Land Elevation*. If it is required to encode the elevation of a triangulation
mark or boundary mark, it must be done using the feature *Landmark*
(see <<sec_7.2>>).

[underline]#Distinction:# Slope Topline; Sloping Ground.

[[sec_5.7]]
=== River

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *RIVER*. A relatively large natural
stream of water. (IHO Dictionary -- S-32)
10+| *[underline]#S-101 Geo Feature:#* *River (RIVERS)*
10+| *[underline]#Primitives:#* *Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_seven]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| status 2+| (STATUS) 3+|
5: periodic/intermittent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_seven]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_seven]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*

|===

[[five_seven]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 20, 21

[[sec_5.7.1]]
==== Rivers (see S-4 -- B-353)

Inland navigable waters must be compiled as fully as practicable,
consistent with the optimum display scale of the ENC data. Other rivers
should be compiled only in a limited way to assist in providing a
general indication of the topography (except close to the coastline
where they may be of direct significance to the Mariner).

If it is required to encode a non-navigable river, stream or creek,
it must be done using the feature *River*.

[underline]#Remarks:#

* If the river is navigable at the optimum display scale for the ENC
data, it must be encoded using the feature *Depth Area*,
*Dredged Area* (see <<sec_11.4>>) or *Unsurveyed Area*, and the riverbanks
must be encoded using the feature *Coastline* or *Shoreline Construction*.
The river must not be encoded as a *River* feature in this case. If
it is required to encode the name of the river, it must be done using
a *Sea Area/Named Water Area* feature with attribute
stem:[bb "category of sea area" = 53] (river).
* Where the river is navigable at the optimum display scale for the
ENC data, special consideration should be given to encoding features
specific to the river such as minimum depths within the navigable
area; overhead clearances; distances along the river; and locks and
lock gates (and any associated traffic signals).
* If it is required to encode a river that is not navigable at the
optimum display scale for the ENC data, it must be done using *River*,
covered by a *Land Area* feature. The name of the river should be
encoded using the complex attribute *feature name* on the *River*
feature.
* Intermittent riversare those that are dry most of the time, and
where required must be encoded as a *River* feature with attribute
stem:[bb "status" = 5] (periodic/intermittent).
* If it is required to encode an island in a non-navigable river encoded
on *Land Area*, this must be done by encoding a "hole" in the *River*
feature if the island is a surface at the optimum display scale for
the ENC data, or encoding *Land Area* of type point if the island
is a point at the optimum display scale for the ENC data. Encoders
must not encode *Land Area* surfaces on top of *Land Area* surfaces.
If it is required to encode an island in a non-navigable river encoded
on *Unsurveyed Area*, this must be done by encoding a "hole" in both
the *River* and *Unsurveyed Area* features and replacing with
*Land Area* if the island is a surface at the optimum display scale
for the ENC data, or encoding *Land Area* of type point if the island
is a point at the optimum display scale for the ENC data. Encoders
must not encode *Land Area* surfaces on top of *Unsurveyed Area* surfaces.
* Some dry riverbeds, known as wadi's, may be prominent topographic
features. If it is required to encode a wadi, it should be done using
a *Land Region* feature (see <<sec_5.11>>), with the name of the wadi
encoded using the complex attribute *feature name*.

[underline]#Distinction:# Canal; Lake; Sea Area/Named Water Area;
Tideway.

[[sec_5.8]]
=== Rapids

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *RAPIDS*. Portions of a stream with
accelerated current where it descends rapidly but without a break
in the slope of the bed sufficient to form a waterfall. Usually used
in the plural. (IHO Dictionary -- S-32).
10+| *[underline]#S-101 Geo Feature:#* *Rapids (RAPIDS)*
10+| *[underline]#Primitives:#* *Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_eight]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| vertical length 2+| (VERLEN) 3+| | RE | 0,1

3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_eight]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_eight]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_eight]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 22

[[sec_5.8.1]]
==== Rapids (see S-4 -- B-353.5)

If it is required to encode rapids within a river, it must be done
using the feature *Rapids*.

[underline]#Remarks:#

* The area covered by rapids must also be covered by a *River* feature
(see <<sec_5.7>>) and a *Land Area* feature if there is no navigable
water adjoining the **Rapids**; or an *Unsurveyed Area* feature if
there is navigable water adjacent to the *Rapids*.

[underline]#Distinction:# Current -- Non-Gravitational; River; Tidal
Stream Panel Data; Water Turbulence; Waterfall.

[[sec_5.9]]
=== Waterfall

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *WATERFALL*. A vertically descending
part of a watercourse where it falls from a height (for example: over
a rock or a precipice). In place names, commonly shortened to fall
or falls, for example Niagara Falls. (Defence Geospatial Information
Working Group; Feature Data Dictionary Register, 2010).
10+| *[underline]#S-101 Geo Feature:#* *Waterfall (WATFAL)*
10+| *[underline]#Primitives:#* *Point, Curve*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_nine]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| vertical length 2+| (VERLEN) 3+| | RE | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_nine]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_nine]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_nine]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 22

[[sec_5.9.1]]
==== Waterfalls (see S-4 -- B-353.5)

If it is required to encode a waterfall within a river, it must be
done using the feature *Waterfall*.

[underline]#Remarks:#

* The area covered by a waterfall must also be covered by a *River*
feature (see <<sec_5.7>>) and a *Land Area*.

[underline]#Distinction:# Rapids; River.

[[sec_5.10]]
=== Lake

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *LAKE*. A large body of water entirely
surrounded by land. (IHO Dictionary -- S-32).
10+| *[underline]#S-101 Geo Feature:#* *Lake (LAKARE)*
10+| *[underline]#Primitives:#* *Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| elevation 2+| (ELEVAT) 3+| | RE | 0,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_ten]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| status 2+| (STATUS) 3+|
5: periodic/intermittent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_ten]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_ten]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*   2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*       2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*      2+| Association | 0,*

|===

[[five_ten]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 23

[[sec_5.10.1]]
==== Lakes (see S-4 -- B-353.6)

Inland navigable waters must be compiled as fully as practicable,
consistent with the optimum display scale of the ENC data. Other lakes
should be compiled only in a limited way to assist in providing a
general indication of the topography (except close to the coastline
where they may be of direct significance to the Mariner).

If it is required to encode a non-navigable lake, it must be done
using the feature *Lake*.

[underline]#Remarks:#

* If the lake is navigable at the optimum display scale for the ENC
data, it must be encoded using the feature *Depth Area*,
*Dredged Area* (see <<sec_11.4>>) or *Unsurveyed Area*, and the lake
shore must be encoded using the feature *Coastline* or
*Shoreline Construction*. The lake must not be encoded as a *Lake*
feature in this case. If it is required to encode the name of the
lake, it must be done using a *Sea Area/Named Water Area* feature,
with attribute stem:[bb "category of sea area" = 52] (lake).
* If it is required to encode a lake that is not navigable at the
optimum display scale for the ENC data, it must be done using *Lake*,
covered by a *Land Area* feature. The name of the lake should be encoded
using the complex attribute *feature name* on the *Lake* feature.
* If it is required to encode an island in a non-navigable lake encoded
on *Land Area*, this must be done by encoding a "hole" in the *Lake*
feature if the island is a surface at the optimum display scale for
the ENC data, or encoding *Land Area* of type point if the island
is a point at the optimum display scale for the ENC data. Encoders
must not encode *Land Area* surfaces on top of *Land Area* surfaces.
If it is required to encode an island in a non-navigable lake encoded
on *Unsurveyed Area*, this must be done by encoding a "hole" in both
the *Lake* and *Unsurveyed Area* features and replacing with
*Land Area* if the island is a surface at the optimum display scale
for the ENC data, or encoding *Land Area* of type point if the island
is a point at the optimum display scale for the ENC data. Encoders
must not encode *Land Area* surfaces on top of *Unsurveyed Area* surfaces.
* Intermittent lakesare those that are dry most of the time, and where
required must be encoded as a *Lake* feature with attribute
stem:[bb "status" = 5] (periodic/intermittent).

[underline]#Distinction:# Canal; Depth Area; River.

[[sec_5.11]]
=== Land region

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *LAND REGION*. An area of natural
or cultivated scenery defined by its geographical characteristics
and may be known by its proper name. (Adapted from S-57 Edition 3.1,
Appendix A -- Chapter 1, Page 1.92, November 2000).
10+| *[underline]#S-101 Geo Feature:#* *Land Region (LNDRGN)*
10+| *[underline]#Primitives:#* *Point, Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of land region 2+| (CATLND) 3+|
1: fen +
2: marsh +
3: bog +
4: heathland +
5: mountain range +
6: lowlands +
7: canyon lands +
8: paddy field +
9: agricultural land +
10: savanna/grassland +
11: parkland +
12: swamp +
13: landslide +
14: lava flow +
15: salt pan +
16: moraine +
17: crater +
18: cave +
19: rock column or pinnacle +
20: cay +
21: wadi | EN | 0,* footnoteblock:[five_eleven]
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,* footnoteblock:[five_eleven]

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_eleven]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| nature of surface 2+| (NATSUR) 3+|
1: mud  +
2: clay +
3: silt +
4: sand +
5: stone +
6: gravel +
7: pebbles +
8: cobbles +
9: rock +
11: lava +
14: coral +
17: shells +
18: boulder | EN | 0,*
3+| water level effect 2+| (WATLEV) 3+|
1: partly submerged at high water +
6: subject to inundation or flooding | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_eleven]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_eleven]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*                      2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*                          2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Contact Details*, *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*                         2+| Association | 0,*

|===

[[five_eleven]]
[NOTE]
--
At least one of the attributes *category of land region* or
*feature name* must be populated.

Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 24, 26, 33

[[sec_5.11.1]]
==== Natural sceneries (see S-4 -- B-350)

If it is required to describe the natural scenery of the land, or
to give the geographic name of an area on land, it should be encoded
using the feature *Land Region*.

[underline]#Remarks:#

* This feature has a use similar to that of the feature
*Sea Area/Named Water Area* (see <<sec_9.1>>), but for the land.
* Sand dunes, hills and cliffs must be encoded, where required, using
the feature classes *Sloping Ground* and/or *Slope Topline* (see <<sec_5.14;and!sec_5.15>>).
* A *Land Region* surface should be bounded, if possible, by existing
curves used by other features (for example *Coastline*). If necessary,
however, this surface may be bounded by other curves created to close
the surface, or to describe a new surface.
* For named capes, points, peninsulas and other types of *Land Region*
where there is no specific value for the attribute
*category of land region*, the generic term "Cape", "Point", "Peninsula",
etc may be included on the complex attribute *feature name*, unless
the name has been populated on an underlying *Land Area*, in which
case *Land Region* should not be encoded.
* *Land Region* features of type surface may overlap.
* For additional guidance on encoding geographic names, see <<sec_2.5.8>>.

[[sec_5.11.1.1]]
===== Marsh (see S-4 -- B-312.2)

If it is required to encode a marshy area behind the coastline, it
must be done using a *Land Region* feature, with attribute
stem:[bb "category of land region" = 2] (marsh).

If the seaward edge of a marsh area is coincident with the coastline,
the coastline should be encoded as a *Coastline* feature, with attribute
stem:[bb "category of coastline" = 8] (marshy shore), and the coastline's
spatial type should have the attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate) for
the visible coastline.

[[sec_5.11.1.2]]
===== Salt pans (see S-4 -- B-353.7)

If it is required to encode an area on land in which seawater is evaporated,
it must be done using a *Land Region* feature, with attribute
stem:[bb "category of land region" = 15] (salt pan) covered by a
*Land Area* feature (that is, the salt pan must not form a hole in
the land area).

If the seaward edge of an encoded salt pan area is coincident with
the coastline, this edge should also be encoded using a *Coastline*
feature, with attribute stem:[bb "category of coastline" = 2]
(flat coast).

[[sec_5.11.1.3]]
===== Lava flow (see S-4 -- B-355)

If it is required to encode a lava flow, it must be done using a
*Land Region* feature, with attribute
stem:[bb "category of land region" = 14] (lava flow).

If the seaward edge of an encoded lava flow area is coincident with
the coastline, this edge should also be encoded using a *Coastline*
feature (see <<sec_5.3>>), with attribute
stem:[bb "nature of surface" = 11] (lava). If the source indicates
that the lava flow is active, the coastline's spatial type should
have the attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate).

[underline]#Distinction:# Land Area; Sea Area/Named Water Area; Slope
Topline; Sloping Ground; Vegetation.

[[sec_5.12]]
=== Vegetation

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *VEGETATION*. Plants collectively
or individually, especially those dominating a particular area or
habitat. (Adapted from Defence Geospatial Information Working Group;
Feature Data Dictionary Register, 2010).
10+| *[underline]#S-101 Geo Feature:#* *Vegetation (VEGATN)*
10+| *[underline]#Primitives:#* *Point, Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of vegetation 2+| (CATVEG) 3+|
3: bush +
4: deciduous wood +
5: coniferous wood +
6: wood in general (inc. mixed wood) +
11: reed +
13: tree in general +
14: evergreen tree +
15: conifer tree +
16: palm tree +
17: nipa palm tree +
18: casuarinas tree +
19: eucalypt tree +
20: deciduous tree +
22: filao tree | EN | 1,1
3+| elevation 2+| (ELEVAT) 3+| | RE | 0,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_twelve]

3+| height 2+| (HEIGHT) 3+| | RE | 0,1

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| vertical length 2+| (VERLEN) 3+| | RE | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_twelve]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_twelve]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*   2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*       2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*      2+| Association | 0,*

|===

[[five_twelve]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 14, 30, 31.1-8, 33

[[sec_5.12.1]]
==== Vegetation (see S-4 -- B-352.4 and B-354)

In most areas the vegetation cover is of negligible importance on
charts with the exception of:

* Areas where trees or marsh form the apparent coastline;
see S-4 -- B-312;
* Isolated trees or clumps of trees forming landmarks;
* Where, near the coast, wooded areas alternate with areas without
tree cover and so may assist in identifying headlands or other stretches
of coastline.
The following features should be omitted from even the largest optimum
display scale ENC data:

* Grassland, cultivated fields (including paddy fields), bushes.
* Trees along roads, fences, ditches, and scattered trees
(unless landmarks).
* Woodland cover within urban areas (unless adjacent to the coast).
* Woodland cover which is the general ground cover and therefore
useless for identification of position.
If it is required to encode an isolated tree used as a landmark,
it must be done using a *Vegetation* feature, with attribute
*category of vegetation* = _13_ to _22_.

[underline]#Remarks:#

* The attribute *height* is used to encode the approximate altitude
of the highest point of the top of the vegetation. Where the source
shows an island with the approximate height of the top of the vegetation
above height datum (see INT1 - C14), a *Vegetation* feature should
be encoded co-incident with the *Land Area* feature of the island,
with attribute *height* corresponding to the value shown on the source.
* Where it is required to encode a mangrove area or tree located in
the intertidal area, this should be done using the feature *Obstruction*
(see <<sec_13.6;and!sec_13.6.1.1>>), with attribute
stem:[bb "categoryof obstruction" = 23] (mangrove).
Where it is required to encode the
generalised seaward edge only of a mangrove area to represent the
"apparent" coastline, this must be done using the feature *Coastline*
(see <<sec_5.3>>).

[underline]#Distinction:# Seabed Area; Seagrass; Weed/Kelp.

[[sec_5.13]]
=== Ice area

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *ICE AREA*. An area of ice over
land or water. (S-57 Edition 3.1, Appendix A -- Chapter 1, Page 1.84,
November 2000).
10+| *[underline]#S-101 Geo Feature:#* *Ice Area (ICEARE)*
10+| *[underline]#Primitives:#* *Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of ice 2+| (CATICE) 3+|
1: fast ice +
5: glacier +
8: polar ice | EN | 1,1
3+| elevation 2+| (ELEVAT) 3+| | RE | 0,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_thirteen]

3+| height 2+| (HEIGHT) 3+| | RE | 0,1

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| periodic date range 2+| 3+| See <<sec_2.4.8>> | C | 0,*

3+| date end 2+| _(PEREND)_ 3+| | (S) TD | 1,1

3+| date start 2+| _(PERSTA)_ 3+| | (S) TD | 1,1

3+| reported date 2+| _(SORDAT)_ 3+| See <<sec_2.4.8>> | TD | 0,1

3+| status 2+| (STATUS) 3+|
1: permanent +
5: periodic/intermittent +
18: existence doubtful | EN | 0,*
3+| vertical length 2+| (VERLEN) 3+| | RE | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_thirteen]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_thirteen]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*

|===

[[five_thirteen]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 25; N 60.1-2

[[sec_5.13.1]]
==== Ice areas (see S-4 -- B-353.8 and B-449.1)

If it is required to encode an ice area, it must be done using the
feature *Ice Area*.

[underline]#Remarks:#

* *Ice Area* features that are located in the sea must be covered
by an *Unsurveyed Area* feature, if the depth of water beneath them
is unknown, or covered by a *Depth Area* feature, if the depth is
known.
* As ice fronts move, a date when the limit was surveyed should be
included, if possible, using the attribute *reported date*.

[[sec_5.13.1.1]]
===== Glaciers (see S-4 -- B-353.8)

If it is required to encode the portion of a glacier that is on land,
it must be done using an *Ice Area* feature, with attribute
stem:[bb "category of ice" = 5] (glacier) covered by a *Land Area*
feature (that is, the glacier does not form a hole in the land area).

If the seaward edge of an encoded glacier is coincident with the coastline,
this edge should be encoded using a *Coastline* feature, with attribute
stem:[bb "category of coastline" = 6] (glacier, seaward end), and
the coastline's spatial type should have the attribute
stem:[bb "quality of horizontal measurement" = 4] (approximate) for
the visible coastline.

[underline]#Distinction:# Depth Area; Land Area.

[[sec_5.14]]
=== Sloping ground

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *SLOPING GROUND*. An inclined surface.
(S-57 Edition 3.1, Appendix A -- Chapter 1, Page 1.161, November 2000).
10+| *[underline]#S-101 Geo Feature:#* *Sloping Ground (SLOGRD)*
10+| *[underline]#Primitives:#* *Point, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of slope 2+| (CATSLO) 3+|
1: cutting +
2: embankment +
3: dune +
4: hill +
5: pingo +
6: cliff +
7: scree | EN | 0,1
3+| colour 2+| (COLOUR) 3+|
1: white +
2: black +
3: red +
4: green +
6: yellow +
7: grey +
8: brown +
11: orange +
13: pink | EN | 0,*
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_fourteen]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| nature of surface 2+| (NATSUR) 3+|
4: sand +
5: stone +
6: gravel +
7: pebbles +
9: rock +
11: lava | EN | 0,*
3+| radar conspicuous 2+| (CONRAD) 3+| | BO | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_fourteen]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_fourteen]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*   2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*       2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*      2+| Association | 0,*
|===

[[five_fourteen]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 3, 4, 8; D 14, 15

[[sec_5.14.1]]
==== Sloping ground (see S-4 -- B-312.1; B-312.3; B-363.2 and B-364.1)

If it is required to encode the characteristics of a prominent or
visually conspicuous inclined land surface, it must be done using
the feature *Sloping Ground*.

[underline]#Remarks:#

* For guidance on the encoding of cuttings and embankments, see <<sec_5.2>>.

[[sec_5.14.1.1]]
===== Dunes, sand hills (see S-4 -- B-312.3)

If it is required to encode a sand dune or sand hill, it must be done
using the feature *Sloping Ground* with attribute
stem:[bb "category of slope" = 3] (dune) or _4_ (hill) and attribute
stem:[bb "nature of surface" = 4] (sand). If these features are positioned
along the coastline, a *Coastline* feature must also be encoded.

If it is required to encode the height of a dune or sand hill, a
*Land Elevation* feature (see <<sec_5.6>>) must also be encoded.

[underline]#Distinction:# Land Elevation; Slope Topline.

[[sec_5.15]]
=== Slope topline

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *SLOPE TOPLINE*. The upper marking
of a slope, for example the ridge line or the separation line between
two different gradients. (S-57 Edition 3.1, Appendix A -- Chapter
1, Page 1.160, November 2000).
10+| *[underline]#S-101 Geo Feature:#* *Slope Topline (SLOTOP)*
10+| *[underline]#Primitives:#* *Curve*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of slope 2+| (CATSLO) 3+|
1: cutting +
2: embankment +
6: cliff | EN | 0,1
3+| colour 2+| (COLOUR) 3+|
1: white +
2: black +
3: red +
4: green +
6: yellow +
7: grey +
8: brown +
11: orange +
13: pink | EN | 0,*
3+| elevation 2+| (ELEVAT) 3+| | RE | 0,1

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_fifteen]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| nature of surface 2+| (NATSUR) 3+|
4: sand +
5: stone +
6: gravel +
7: pebbles +
9: rock +
11: lava | EN | 0,*
3+| radar conspicuous 2+| (CONRAD) 3+| | BO | 0,1

3+| visual prominence 2+| (CONVIS) 3+|
1: visually conspicuous +
2: not visually conspicuous +
3: prominent | EN | 0,1
3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_fifteen]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_fifteen]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*   2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*       2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*      2+| Association | 0,*

|===

[[five_fifteen]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:# C 3; D 14, 15

[[sec_5.15.1]]
==== Slope topline (see S-4 -- B-312.1; B-363.2 and B-364.1)

If it is required to encode the upper marking of a prominent or visually
conspicuous land slope, it must be done using the feature *Slope Topline*.

[underline]#Remarks:#

* For guidance on the encoding of cliffs, see <<sec_5.1>>. For guidance
on the encoding of cuttings and embankments, see <<sec_5.2>>.

[underline]#Distinction:# Coastline; Land Elevation; Sloping Ground.

[[sec_5.16]]
=== Tideway

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *TIDEWAY*. A channel through which
a tidal current runs. (IHO Dictionary -- S-32).
10+| *[underline]#S-101 Geo Feature:#* *Tideway (TIDEWY)*
10+| *[underline]#Primitives:#* *Curve, Surface*

2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,*

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN
| 0,1 footnoteblock:[five_sixteen]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1

3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnoteblock:[five_sixteen]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnoteblock:[five_sixteen]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+h| Type h| Multiplicity
| The Updated Object    3+| *Updated Information* (see <<sec_25.21>>)   3+| *Update Information*   2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>).     3+| *Text Placement*       2+| Composition | 0,1
| -                     3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| -                     3+| *Spatial Association* (see <<sec_25.15>>)   3+| *Spatial Quality*      2+| Association | 0,*

|===

[[five_sixteen]]
[NOTE]
--
Complex attribute *feature name*, sub-attribute *name usage* is mandatory
if the name is intended to be displayed when display of names is enabled
by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes
*file reference* or *text* must be populated.
--

[underline]#INT 1 Reference:#

[[sec_5.16.1]]
==== Tideways (see S-4 -- B-413.3)

If it is required to encode a natural watercoursein intertidal areas,
for example formed by the outflow of a stream or by tidal action,
it must be done using the feature *Tideway*.

[underline]#Remarks:#

* No remarks.

[underline]#Distinction:# Canal; River; Sea Area/Named Water Area.