
[[sec_9]]
== Geo Features – Topographic Terms

[[sec_9.1]]
=== Sea area/named water area

[cols="10", options="unnumbered"]
|===
10+| [underline]#IHO Definition:# *SEA AREA/NAMED WATER AREA*. A geographically defined part of the sea or other navigable waters. It may be specified within its limits by its proper name. (S-57 Edition 3.1, Appendix A -- Chapter 1, Page 1.151, November 2000).
10+| *[underline]#S-101 Geo Feature:#* *Sea Area/Named Water Area (SEAARE)*
10+| *[underline]#Primitives:#* *Point, Surface*
2+| _Real World_ 4+| _Paper Chart Symbol_ 4+| _ECDIS Symbol_

3+h| S-101 Attribute 2+h| S-57 Acronym 3+h| Allowable Encoding Value h| Type h| Multiplicity
3+| category of sea area 2+| (CATSEA)
3+|
2: gat +
3: bank +
4: deep +
5: bay +
6: trench +
7: basin +
8: mud flats +
9: reef +
10: ledge +
11: canyon +
12: narrows +
13: shoal +
14: knoll +
15: ridge +
16: seamount +
17: pinnacle +
18: abyssal plain +
19: plateau +
20: spur +
21: shelf +
22: trough +
23: saddle +
24: abyssal hill +
25: apron +
26: archipelagic apron +
27: borderland +
28: continental margin +
29: continental rise +
30: escarpment +
31: fan +
32: fracture zone +
33: gap +
34: guyot +
35: hill +
36: hole +
37: levee +
38: median valley +
39: moat +
40: mountains +
41: peak +
42: province +
43: rise +
44: sea channel +
45: seamount chain +
46: shelf-edge +
47: sill +
48: slope +
49: terrace +
50: valley +
51: canal +
52: lake +
53: river +
54: reach +
55: intertidal cay +
56: submarine volcano | EN | 0,1
footnote:ninedotone[At least one of the attributes *category of sea area* or *feature name* must be populated.]

3+| feature name 2+| 3+| See <<sec_2.5.8>> | C | 0,* footnote:ninedotone[]

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| name 2+| _(OBJNAM) (NOBJNM)_ 3+| | (S) TE | 1,1

3+| name usage 2+| 3+|
1: default name display +
2: alternate name display | (S) EN | 0,1 footnote:ninedotone[]

3+| interoperability identifier 2+| 3+| MRN (see <<sec_27.114>>) | URN | 0,1

3+| scale minimum 2+| (SCAMIN) 3+| See <<sec_2.5.9>> | IN | 0,1
3+| information 2+| 3+| See <<sec_2.4.6>> | C | 0,*

3+| file locator 2+| 3+| | (S) TE | 0,1

3+| file reference 2+| _(TXTDSC) (NTXTDS)_ 3+| | (S) TE | 0,1 footnote:ninedotone[]

3+| headline 2+| 3+| | (S) TE | 0,1

3+| language 2+| 3+| ISO 639-2/T | (S) TE | 1,1

3+| text 2+| _(INFORM) (NINFOM)_ 3+| | (S) TE | 0,1 footnote:ninedotone[]

10+h| Feature Associations
h| S-101 Role 3+h| Association Type 3+h| Associated to 2+| *Type* | *Multiplicity*
| The Updated Object 3+| *Updated Information* (see <<sec_25.21>>) 3+| *Update Information* 2+| Association | 0,*
| The Position Provider 3+| *Text Association* (see <<sec_25.17>>). 3+| *Text Placement* 2+| Composition | 0,1
| - 3+| *Additional Information* (see <<sec_25.1>>) 3+| *Nautical Information* 2+| Association | 0,*
| - 3+| *Spatial Association* (see <<sec_25.15>>) 3+| *Spatial Quality* 2+| Association | 0,*
|===

Complex attribute *feature name*, sub-attribute *name usage* is mandatory if the name is intended to be displayed when display of names is enabled by the Mariner. See <<sec_2.5.8>>.

For each instance of *information*, at least one of the sub-attributes *file reference* or *text* must be populated.

[underline]#INT 1 Reference:#

[[sec_9.1.1]]
==== Sea areas (see S-4 – B-550)

Undersea features and sea areas in general, including intertidal areas, may be identified by their names and may be delimited by the spatial types used by other geo features (for example depth contours, coastlines). If it is required to encode these areas, this must be done using the feature *Sea Area/Named Water Area*.

[underline]#Remarks:#

* This feature has a use similar to that of the feature *Land Region* (see <<sec_5.11>>), but for the sea.
* A *Sea Area/Named Water Area* feature of type surface should be bounded, if possible, by existing curves used by other features (for example *Depth Contour*, *Coastline*). If necessary, however, this surface may be bounded by other curves created to close the surface, or to describe a new surface.
* *Sea Area/Named Water Area* features of type surface may overlap.
* Inactive submarine volcanos must be encoded, if required, as *Sea Area* with *category of sea area* = _56_ (submarine volcano). Active submarine volcanos must be encoded, if required, using an *Obstruction* feature (see <<sec_13.6>>).
* For additional guidance on encoding geographic names, see <<sec_2.5.8>>.

[underline]#Distinction:# Administration Area; Depth Area; Seabed Area.
