
[.preface]
== metanorma-extension

[.boilerplate]
--
Changes to this Specification are coordinated by the S-101 Project
Team (S-101PT), a Project Team under the IHO S-100 Working Group (S-100WG).
New editions will be made available via the IHO web site. Maintenance
of the Specification shall conform to IHO Resolution 2/2007 (as amended).
--

=== document history

[source,yaml]
----
- date:
  - type: updated
    value: 2009-05
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Initial Draft.
- date:
  - type: updated
    value: 2010-06
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Merged all the phases back into a single document.
- date:
  - type: updated
    value: 2010-07
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Added comments from AHO.
- date:
  - type: updated
    value: 2010-09
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Revised based on FG discussions.
- date:
  - type: updated
    value: 2010-12
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Revised based on TSMAD 21.
- date:
  - type: updated
    value: 2011-02
  edition: "Phase 1"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Revised based on comments to phase 1 from 2J, FR, AU.
- date:
  - type: updated
    value: 2011-04
  edition: "Phase 2"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Revised based on comments from TSMAD22. Changed version to 0.1.0 to reflect movement to phase 2.
- date:
  - type: updated
    value: 2011-11
  edition: "Phase 2"
  contributor:
  - person:
      name:
        completename: J. Powell
  amend:
    - description: Revisions made based on comments from discussion papers circulated post TSMAD 22.
- date:
  - type: updated
    value: 2012-02
  edition: "Phase 3"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Revisions made based on TSMAD23 decisions.
- date:
  - type: updated
    value: 2012-05
  edition: "Phase 3"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Added TSMAD24 Decisions into document.
- date:
  - type: updated
    value: 2012-08
  edition: "Phase 4"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Edited document to reflect TSMAD24 decisions.
- date:
  - type: updated
    value: 2012-11
  edition: "Phase 4"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Added comments from October 2012 round of TSMAD comments.
- date:
  - type: updated
    value: 2013-03
  edition: "Initial Draft"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Added comments from January 2013 round of TSMAD comments.
- date:
  - type: updated
    value: 2013-06
  edition: "Initial Draft"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Added decisions from TSMAD26.
- date:
  - type: updated
    value: 2013-12
  edition: "Initial Draft"
  contributor:
  - person:
      name:
        completename: J.Powell
  amend:
    - description: Added in decisions from TSMAD27.
- date:
  - type: updated
    value: 2014-05
  edition: "Draft 0.0.0"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: Included S-101 portrayal. Most of the portrayal is covered by the catalogue, so much of the old S-52 guidance goes into the implementation guidance annex.
- date:
  - type: updated
    value: 2015-02
  edition: "Draft 0.0.1"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: Added adjudicated comments from TSMAD29.
- date:
  - type: updated
    value: 2016-01
  edition: "Draft 0.0.2"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: Incorporated editorial issues that were noted in draft 0.0.1. Also includes a revised metadata section.
- date:
  - type: updated
    value: 2017-07
  edition: "Draft 0.0.2"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: Incorporated the decisions from S101PT1 and updated some editorial issues. Numbering remained the same to be consistent with the DCEG numbering.
- date:
  - type: updated
    value: 2018-10
  edition: "Draft 1.0.0"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: Editorial S-101PT review and clean-up in preparation for final approval to publish as Edition 1.0.0.
- date:
  - type: updated
    value: 2022-12
  edition: "Draft 1.1.0"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: New version for implementation and testing, updated to align with S-100 Edition 5.0.0.
- date:
  - type: updated
    value: 2024-03
  edition: "Draft 1.2.0"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: S-100 Working Group
      abbreviation: S-100WG
  amend:
    - description: New version for implementation and testing, updated to align with S-100 Edition 5.1.0.
- date:
  - type: updated
    value: 2024-12
  edition: "Draft 2.0.0"
  contributor:
  - organization:
      name: International Hydrographic Organization
      subdivision: IHO CL 02-2025
  amend:
    - description: Initial operational Edition of S-101, updated to align with S-100 Edition 5.2.0.
----

[.preface]
== Summary of Substantive Changes from Edition 2.0.0

*Bold* references in the Clauses Effected column indicate the principle
sections/clauses that are impacted by the described change.

[cols="a,a",options="unnumbered"]
|===
h| Change Summary h| Clauses Affected

| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
| |
|===

== Introduction

S-101 is the Electronic Navigational Chart (ENC) Product Specification,
produced by the International Hydrographic Organization. S-101 is
designed to allow content, content definition (Feature Catalogues)
and presentation (Portrayal Catalogues) to be updateable as
"Plug and Play" system implementations.

Based on the IHO Universal Hydrographic Data Model S-100, S-101 includes
all the necessary components for both Hydrographic Offices to produce
Electronic Navigational Charts (ENCs); and marine navigation systems
(principally Electronic Chart Display and Information Systems (ECDIS))
to be able to ingest and properly display them. This Product Specification
is designed to be flexible with the introduction of machine-readable
Feature and Portrayal Catalogues that will allow for managed change;
and will enable the introduction of new navigationally significant
features and their portrayal using a "just in time" methodology.