
[[sec_10]]
== Data Product Format (Encoding)

[[sec_10.1]]
=== Introduction

This clause specifies the encoding for S-101 datasets.
See <<annexB>> for a complete description of the data records,
fields and subfields defined in the encoding.

*Format Name:*:: ISO/IEC 8211

*Character Set:*:: ISO 10646 Base Multilingual Plane

*Specification:*:: S-100 profile of ISO/IEC 8211 (S-100 Part 10A)

[[sec_10.1.1]]
==== Encoding of latitude and longitude

Coordinates are stored as integers. Latitude and longitude are converted
to integers using a multiplication factor held in the Dataset Structure
Information field under [CMFX] and [CMFY] (see <<sec_B-5.1.2>>).

These coordinate multiplication factors must be set to
stem:[{10000000} (10^7)] for all datasets.

[example]
A stem:["longitude" = 42.0000] is converted into stem:[X = "longitude" ** "CMFX" = 42.0000 ** 10000000 = 420000000].

[[sec_10.1.2]]
==== Encoding of depths as coordinates

Depths are converted from decimal metres to integers by means of the
[CMFZ] (see <<sec_B-5.1.2>>). This Product Specification limits the
resolution to one decimal place and therefore the [CMFZ] must be set
to {10}.

[example]
A stem:["depth" = 4.2] is converted in
stem:[Z = "depth" ** "CMFZ" = 4.2 ** 10 = 42]

NOTE: This does not apply to depth encoded as attributes.

[[sec_10.1.3]]
==== Numeric attribute encoding

Floating point and integer attribute values must not contain leading
zeros. Floating point attribute values must not contain non-significant
trailing zeros.

[[sec_10.1.4]]
==== Text attribute values

Character strings must be encoded using the character set defined
in ISO 10646-1, in Unicode Transformation Format-8 (UTF-8).

[[sec_10.1.5]]
==== Unknown attribute values

In a Base dataset, when an attribute code is present, but the attribute
value is missing, it means that the producer wishes to indicate that
this attribute value is unknown.

In an Update dataset, when an attribute code is present, but the attribute
value is missing it means:

* that the value of this attribute is to be replaced by an empty (null)
value if it was present in the original dataset; or

* that an empty (null) value is to be inserted if the attribute was
not present in the original dataset.
